### PR TITLE
feat(STONEINTG-892): Include git url override snapshot example

### PR DESCRIPTION
**Pull request by simonbaird**
Include the git url as well as the revision, and add some additional explanation about the source key. (Commit messages have some additional notes.)

This is a followup for #274.

See also [KFLUXBUGS-1376](https://issues.redhat.com/browse/KFLUXBUGS-1376).

[STONEINTG-892](https://issues.redhat.com/browse/STONEINTG-892)

### CODE REVIEW

**Comment by simonbaird** [comment]
FYI @hongweiliu17 @dirgim

**Comment by simonbaird** [comment]
See also https://github.com/konflux-ci/integration-examples/pull/33 .

**Review by hongweiliu17 — APPROVED** [review]
Thanks! LGTM

**Review by dirgim — APPROVED** [review]
LGTM

**Review by lcarva — APPROVED** [review]

**Comment by arewm** [comment]
The redhat-appstudio docs are deprecated. Would you be able to recreate a similar PR on [konflux-ci/docs](https://github.com/konflux-ci/docs)?

**Comment by simonbaird** [comment]
> The redhat-appstudio docs are deprecated. Would you be able to recreate a similar PR on [konflux-ci/docs](https://github.com/konflux-ci/docs)?

Already done over there, see https://github.com/konflux-ci/docs/pull/74

**Comment by lcarva** [comment]
Great! Let's close this out then?

**Comment by simonbaird** [comment]
@arewm merge maybe?

**Comment by arewm** [comment]
I have no permissions on this repository, unfortunately.

**Comment by dirgim** [comment]
I seem to have the permissions, I will merge this to keep consistency with the [konflux-ci/docs](https://github.com/konflux-ci/docs).

**Pull request merged**
